[package]
name = "clob-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.48.0", features = ["net", "macros", "rt-multi-thread", "io-util"] }
anyhow = "1.0"
bytes = "1"
